/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/Texture/PatternTwo copy.vue')['default']
    MainBanner: typeof import('./src/components/Layout/MainBanner.vue')['default']
    MainLogo: typeof import('./src/components/Material/MainLogo.vue')['default']
    PatternMaterial: typeof import('./src/components/Material/PatternMaterial.vue')['default']
    PatternOne: typeof import('./src/components/Texture/PatternOne.vue')['default']
    PatternThree: typeof import('./src/components/Texture/PatternThree.vue')['default']
    PatternTwo: typeof import('./src/components/Texture/PatternTwo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
