/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MainBanner: typeof import('./src/components/Layout/MainBanner.vue')['default']
    MainFooter: typeof import('./src/components/Layout/MainFooter.vue')['default']
    MainLogo: typeof import('./src/components/Material/MainLogo.vue')['default']
    MainNavbar: typeof import('./src/components/Layout/MainNavbar.vue')['default']
    PatternMaterial: typeof import('./src/components/Material/PatternMaterial.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Session: typeof import('./src/components/Layout/Session.vue')['default']
    SessionInfo: typeof import('./src/components/Layout/SessionInfo.vue')['default']
    SessionList: typeof import('./src/components/Layout/SessionList.vue')['default']
  }
}
